
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 10 2026 02:24:09 AKDT (Apr 10 2026 10:24:09 UTC)

// Verification Directory fv/up_down_counter_8bit 

module up_down_counter_8bit(clk, reset, up_down, count);
  input clk, reset, up_down;
  output [7:0] count;
  wire clk, reset, up_down;
  wire [7:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, \count[0]_62 , n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  JKFFRXL \count_reg[7] (.RN (n_19), .CK (clk), .J (n_20), .K (n_20),
       .Q (count[7]), .QN (UNCONNECTED));
  JKFFRXL \count_reg[6] (.RN (n_19), .CK (clk), .J (n_18), .K (n_18),
       .Q (count[6]), .QN (UNCONNECTED0));
  AOI211X1 g549__2398(.A0 (n_14), .A1 (count[6]), .B0 (n_16), .C0
       (n_2), .Y (n_20));
  JKFFRXL \count_reg[5] (.RN (n_19), .CK (clk), .J (n_17), .K (n_17),
       .Q (count[5]), .QN (n_0));
  INVXL g551(.A (n_16), .Y (n_18));
  JKFFRXL \count_reg[3] (.RN (n_19), .CK (clk), .J (n_15), .K (n_15),
       .Q (count[3]), .QN (UNCONNECTED1));
  OAI221XL g552__5107(.A0 (n_14), .A1 (count[5]), .B0 (n_0), .B1
       (count[4]), .C0 (n_17), .Y (n_16));
  JKFFRXL \count_reg[4] (.RN (n_19), .CK (clk), .J (n_13), .K (n_13),
       .Q (count[4]), .QN (n_14));
  AOI221X1 g555__6260(.A0 (n_14), .A1 (up_down), .B0 (n_10), .B1
       (count[4]), .C0 (n_9), .Y (n_17));
  JKFFRXL \count_reg[2] (.RN (n_19), .CK (clk), .J (n_12), .K (n_12),
       .Q (count[2]), .QN (n_1));
  AOI221X1 g554__4319(.A0 (n_1), .A1 (count[0]), .B0 (\count[0]_62 ),
       .B1 (count[2]), .C0 (n_5), .Y (n_15));
  SDFFRHQX1 \count_reg[1] (.RN (n_19), .CK (clk), .D (up_down), .SI
       (n_10), .SE (n_4), .Q (count[1]));
  INVX1 g557(.A (n_8), .Y (n_9));
  AOI22X1 g556__8428(.A0 (n_7), .A1 (n_10), .B0 (n_6), .B1 (up_down),
       .Y (n_13));
  AOI22X1 g559__5526(.A0 (n_7), .A1 (n_14), .B0 (n_6), .B1 (count[4]),
       .Y (n_8));
  INVXL g558(.A (n_12), .Y (n_5));
  AOI221X1 g560__6783(.A0 (up_down), .A1 (\count[0]_62 ), .B0 (n_10),
       .B1 (count[1]), .C0 (n_3), .Y (n_12));
  NAND4X1 g561__3680(.A (count[0]), .B (count[2]), .C (count[1]), .D
       (count[3]), .Y (n_6));
  AOI21X1 g563__1617(.A0 (\count[0]_62 ), .A1 (count[1]), .B0 (n_3), .Y
       (n_4));
  OR4X1 g562__2802(.A (count[3]), .B (count[1]), .C (count[2]), .D
       (count[0]), .Y (n_7));
  DFFRX1 \count_reg[0] (.RN (n_19), .CK (clk), .D (\count[0]_62 ), .Q
       (count[0]), .QN (\count[0]_62 ));
  NOR2X1 g565__1705(.A (n_14), .B (count[6]), .Y (n_2));
  NOR2X1 g566__5122(.A (\count[0]_62 ), .B (count[1]), .Y (n_3));
  INVX1 g568(.A (up_down), .Y (n_10));
  INVXL g571(.A (reset), .Y (n_19));
endmodule
